### ISSUE TITLE
插件报错无法使用

### ISSUE THREAD

**Issue by Cobyqwq** [ApliNi/useTranslatedNames#5]
purpur1.20.4
CoreProtect-22.2
ProtocolLib 5.2.0

玩家进入直接报错,并且查询也还是英文
[UseTranslatedNames] Unhandled exception occurred in onPacketSending(PacketEvent) for UseTranslatedNames
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:244) ~[ProtocolLib (4).jar:?]
	at aplini.usetranslatednames.UseTranslatedNames$1.onPacketSending(UseTranslatedNames.java:51) ~[useTranslatedNames.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib (4).jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib (4).jar:?]
	at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
	at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:289) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:2151) ~[?:?]
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:1443) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.players.PlayerList.broadcastSystemMessage(PlayerList.java:1429) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:354) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1485) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1462) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1363) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2118]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:34:13] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.ClientboundSystemChatPacket@2b5df384[
    a=io.papermc.paper.adventure.AdventureComponent@284bc6bc
    b=false
  ]

**Comment by ApliNi** [comment]
我还没开始适配新的 ProtocolLib, 请试试这个版本能否正常运行, 需要删除或更新配置文件

--> [useTranslatedNames.zip](https://github.com/ApliNi/useTranslatedNames/files/13972648/useTranslatedNames.zip) <--

记得解压压缩包

**Comment by Cobyqwq** [comment]
> 我还没开始适配新的 ProtocolLib, 请试试这个版本能否正常运行, 需要删除或更新配置文件
> 
> --> [useTranslatedNames.zip](https://github.com/ApliNi/useTranslatedNames/files/13972648/useTranslatedNames.zip) <--
> 
> 记得解压压缩包

测试了，确实可以正常使用了，感谢
