### ISSUE TITLE
请求支持 folia 1.20.6

### ISSUE THREAD

**Issue by x1aoren** [ApliNi/useTranslatedNames#7]
请求支持 folia 1.20.6

**Comment by x1aoren** [comment]
[16:23:16 INFO]: [UTN] Enabling UseTranslatedNames v2.3.1
[16:23:17 INFO]: [UTN] 已加载 84 个实体和 1060 个物品
[16:23:17 ERROR]: Error occurred while enabling UseTranslatedNames v2.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at [U][查熊-优化名称]useTranslatedNames.jar/aplini.usetranslatednames.UseTranslatedNames.onEnable(UseTranslatedNames.java:96) ~[[U][查熊-优化名称]useTranslatedNames.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:717) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[16:23:17 INFO]: [UTN] Disabling UseTranslatedNames v2.3.1
